# Generated by Django 2.2.3 on 2022-08-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='职位名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '职位表',
                'verbose_name_plural': '职位表',
            },
        ),
        migrations.CreateModel(
            name='SavorTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='团队成员名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='NFT头像')),
                ('introduce', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='成员介绍')),
                ('position', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='团队内部职位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '团队成员介绍表',
                'verbose_name_plural': '团队成员介绍表',
            },
        ),
        migrations.CreateModel(
            name='WantJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('weichat', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='微信')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='手机号码')),
                ('experience', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='项目经验')),
                ('skill', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='技能')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_relate', to='web.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': '加入表',
                'verbose_name_plural': '加入表',
            },
        ),
    ]
